/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as SuperadminRouteImport } from './routes/superadmin'
import { Route as StudentRouteImport } from './routes/student'
import { Route as DirectorRouteImport } from './routes/director'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeacherIndexRouteImport } from './routes/teacher.index'
import { Route as SuperadminIndexRouteImport } from './routes/superadmin.index'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as DirectorIndexRouteImport } from './routes/director.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TeacherStudentsRouteImport } from './routes/teacher.students'
import { Route as TeacherSatisfactionRouteImport } from './routes/teacher.satisfaction'
import { Route as TeacherReportsRouteImport } from './routes/teacher.reports'
import { Route as TeacherMessagesRouteImport } from './routes/teacher.messages'
import { Route as TeacherGradesRouteImport } from './routes/teacher.grades'
import { Route as TeacherExamsRouteImport } from './routes/teacher.exams'
import { Route as TeacherDashboardRouteImport } from './routes/teacher.dashboard'
import { Route as TeacherCoursesRouteImport } from './routes/teacher.courses'
import { Route as TeacherAttendanceRouteImport } from './routes/teacher.attendance'
import { Route as SuperadminUsersRouteImport } from './routes/superadmin.users'
import { Route as SuperadminStrategicRouteImport } from './routes/superadmin.strategic'
import { Route as SuperadminPredictionsRouteImport } from './routes/superadmin.predictions'
import { Route as SuperadminOffersRouteImport } from './routes/superadmin.offers'
import { Route as SuperadminMonitoringRouteImport } from './routes/superadmin.monitoring'
import { Route as SuperadminMessagesRouteImport } from './routes/superadmin.messages'
import { Route as SuperadminInstitutionsRouteImport } from './routes/superadmin.institutions'
import { Route as SuperadminFinancialRouteImport } from './routes/superadmin.financial'
import { Route as SuperadminEmploymentEquityRouteImport } from './routes/superadmin.employment-equity'
import { Route as SuperadminDemandsRouteImport } from './routes/superadmin.demands'
import { Route as SuperadminDashboardRouteImport } from './routes/superadmin.dashboard'
import { Route as SuperadminCoordinationRouteImport } from './routes/superadmin.coordination'
import { Route as SuperadminAcademicRouteImport } from './routes/superadmin.academic'
import { Route as StudentStudentLifeRouteImport } from './routes/student.student-life'
import { Route as StudentScheduleRouteImport } from './routes/student.schedule'
import { Route as StudentProfileRouteImport } from './routes/student.profile'
import { Route as StudentMessagesRouteImport } from './routes/student.messages'
import { Route as StudentInternshipsRouteImport } from './routes/student.internships'
import { Route as StudentGradesRouteImport } from './routes/student.grades'
import { Route as StudentFormsRouteImport } from './routes/student.forms'
import { Route as StudentEnrollmentRouteImport } from './routes/student.enrollment'
import { Route as StudentEducationalPathRouteImport } from './routes/student.educational-path'
import { Route as StudentDocumentsRouteImport } from './routes/student.documents'
import { Route as StudentDashboardRouteImport } from './routes/student.dashboard'
import { Route as StudentAttendanceRouteImport } from './routes/student.attendance'
import { Route as DirectorStaffRouteImport } from './routes/director.staff'
import { Route as DirectorReportsRouteImport } from './routes/director.reports'
import { Route as DirectorMessagesRouteImport } from './routes/director.messages'
import { Route as DirectorMeetingsRouteImport } from './routes/director.meetings'
import { Route as DirectorFinancialRouteImport } from './routes/director.financial'
import { Route as DirectorDashboardRouteImport } from './routes/director.dashboard'
import { Route as DirectorApprovalsRouteImport } from './routes/director.approvals'
import { Route as DirectorAlertsRouteImport } from './routes/director.alerts'
import { Route as DirectorAcademicRouteImport } from './routes/director.academic'
import { Route as AdminStrategicRouteImport } from './routes/admin.strategic'
import { Route as AdminResearchRouteImport } from './routes/admin.research'
import { Route as AdminPartnershipsRouteImport } from './routes/admin.partnerships'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminHrRouteImport } from './routes/admin.hr'
import { Route as AdminFinanceRouteImport } from './routes/admin.finance'
import { Route as AdminEsgRouteImport } from './routes/admin.esg'
import { Route as AdminDemandsRouteImport } from './routes/admin.demands'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'

const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminRoute = SuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectorRoute = DirectorRouteImport.update({
  id: '/director',
  path: '/director',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeacherRoute,
} as any)
const SuperadminIndexRoute = SuperadminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperadminRoute,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const DirectorIndexRoute = DirectorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DirectorRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TeacherStudentsRoute = TeacherStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherSatisfactionRoute = TeacherSatisfactionRouteImport.update({
  id: '/satisfaction',
  path: '/satisfaction',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherReportsRoute = TeacherReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherMessagesRoute = TeacherMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherGradesRoute = TeacherGradesRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherExamsRoute = TeacherExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherDashboardRoute = TeacherDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherCoursesRoute = TeacherCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherAttendanceRoute = TeacherAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => TeacherRoute,
} as any)
const SuperadminUsersRoute = SuperadminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminStrategicRoute = SuperadminStrategicRouteImport.update({
  id: '/strategic',
  path: '/strategic',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminPredictionsRoute = SuperadminPredictionsRouteImport.update({
  id: '/predictions',
  path: '/predictions',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminOffersRoute = SuperadminOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminMonitoringRoute = SuperadminMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminMessagesRoute = SuperadminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminInstitutionsRoute = SuperadminInstitutionsRouteImport.update({
  id: '/institutions',
  path: '/institutions',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminFinancialRoute = SuperadminFinancialRouteImport.update({
  id: '/financial',
  path: '/financial',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminEmploymentEquityRoute =
  SuperadminEmploymentEquityRouteImport.update({
    id: '/employment-equity',
    path: '/employment-equity',
    getParentRoute: () => SuperadminRoute,
  } as any)
const SuperadminDemandsRoute = SuperadminDemandsRouteImport.update({
  id: '/demands',
  path: '/demands',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminDashboardRoute = SuperadminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminCoordinationRoute = SuperadminCoordinationRouteImport.update({
  id: '/coordination',
  path: '/coordination',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminAcademicRoute = SuperadminAcademicRouteImport.update({
  id: '/academic',
  path: '/academic',
  getParentRoute: () => SuperadminRoute,
} as any)
const StudentStudentLifeRoute = StudentStudentLifeRouteImport.update({
  id: '/student-life',
  path: '/student-life',
  getParentRoute: () => StudentRoute,
} as any)
const StudentScheduleRoute = StudentScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRoute,
} as any)
const StudentMessagesRoute = StudentMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => StudentRoute,
} as any)
const StudentInternshipsRoute = StudentInternshipsRouteImport.update({
  id: '/internships',
  path: '/internships',
  getParentRoute: () => StudentRoute,
} as any)
const StudentGradesRoute = StudentGradesRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => StudentRoute,
} as any)
const StudentFormsRoute = StudentFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => StudentRoute,
} as any)
const StudentEnrollmentRoute = StudentEnrollmentRouteImport.update({
  id: '/enrollment',
  path: '/enrollment',
  getParentRoute: () => StudentRoute,
} as any)
const StudentEducationalPathRoute = StudentEducationalPathRouteImport.update({
  id: '/educational-path',
  path: '/educational-path',
  getParentRoute: () => StudentRoute,
} as any)
const StudentDocumentsRoute = StudentDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => StudentRoute,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAttendanceRoute = StudentAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => StudentRoute,
} as any)
const DirectorStaffRoute = DirectorStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => DirectorRoute,
} as any)
const DirectorReportsRoute = DirectorReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DirectorRoute,
} as any)
const DirectorMessagesRoute = DirectorMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => DirectorRoute,
} as any)
const DirectorMeetingsRoute = DirectorMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => DirectorRoute,
} as any)
const DirectorFinancialRoute = DirectorFinancialRouteImport.update({
  id: '/financial',
  path: '/financial',
  getParentRoute: () => DirectorRoute,
} as any)
const DirectorDashboardRoute = DirectorDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DirectorRoute,
} as any)
const DirectorApprovalsRoute = DirectorApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => DirectorRoute,
} as any)
const DirectorAlertsRoute = DirectorAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => DirectorRoute,
} as any)
const DirectorAcademicRoute = DirectorAcademicRouteImport.update({
  id: '/academic',
  path: '/academic',
  getParentRoute: () => DirectorRoute,
} as any)
const AdminStrategicRoute = AdminStrategicRouteImport.update({
  id: '/strategic',
  path: '/strategic',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResearchRoute = AdminResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPartnershipsRoute = AdminPartnershipsRouteImport.update({
  id: '/partnerships',
  path: '/partnerships',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHrRoute = AdminHrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEsgRoute = AdminEsgRouteImport.update({
  id: '/esg',
  path: '/esg',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDemandsRoute = AdminDemandsRouteImport.update({
  id: '/demands',
  path: '/demands',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/director': typeof DirectorRouteWithChildren
  '/student': typeof StudentRouteWithChildren
  '/superadmin': typeof SuperadminRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/demands': typeof AdminDemandsRoute
  '/admin/esg': typeof AdminEsgRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/hr': typeof AdminHrRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/partnerships': typeof AdminPartnershipsRoute
  '/admin/research': typeof AdminResearchRoute
  '/admin/strategic': typeof AdminStrategicRoute
  '/director/academic': typeof DirectorAcademicRoute
  '/director/alerts': typeof DirectorAlertsRoute
  '/director/approvals': typeof DirectorApprovalsRoute
  '/director/dashboard': typeof DirectorDashboardRoute
  '/director/financial': typeof DirectorFinancialRoute
  '/director/meetings': typeof DirectorMeetingsRoute
  '/director/messages': typeof DirectorMessagesRoute
  '/director/reports': typeof DirectorReportsRoute
  '/director/staff': typeof DirectorStaffRoute
  '/student/attendance': typeof StudentAttendanceRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/documents': typeof StudentDocumentsRoute
  '/student/educational-path': typeof StudentEducationalPathRoute
  '/student/enrollment': typeof StudentEnrollmentRoute
  '/student/forms': typeof StudentFormsRoute
  '/student/grades': typeof StudentGradesRoute
  '/student/internships': typeof StudentInternshipsRoute
  '/student/messages': typeof StudentMessagesRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/schedule': typeof StudentScheduleRoute
  '/student/student-life': typeof StudentStudentLifeRoute
  '/superadmin/academic': typeof SuperadminAcademicRoute
  '/superadmin/coordination': typeof SuperadminCoordinationRoute
  '/superadmin/dashboard': typeof SuperadminDashboardRoute
  '/superadmin/demands': typeof SuperadminDemandsRoute
  '/superadmin/employment-equity': typeof SuperadminEmploymentEquityRoute
  '/superadmin/financial': typeof SuperadminFinancialRoute
  '/superadmin/institutions': typeof SuperadminInstitutionsRoute
  '/superadmin/messages': typeof SuperadminMessagesRoute
  '/superadmin/monitoring': typeof SuperadminMonitoringRoute
  '/superadmin/offers': typeof SuperadminOffersRoute
  '/superadmin/predictions': typeof SuperadminPredictionsRoute
  '/superadmin/strategic': typeof SuperadminStrategicRoute
  '/superadmin/users': typeof SuperadminUsersRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/courses': typeof TeacherCoursesRoute
  '/teacher/dashboard': typeof TeacherDashboardRoute
  '/teacher/exams': typeof TeacherExamsRoute
  '/teacher/grades': typeof TeacherGradesRoute
  '/teacher/messages': typeof TeacherMessagesRoute
  '/teacher/reports': typeof TeacherReportsRoute
  '/teacher/satisfaction': typeof TeacherSatisfactionRoute
  '/teacher/students': typeof TeacherStudentsRoute
  '/admin/': typeof AdminIndexRoute
  '/director/': typeof DirectorIndexRoute
  '/student/': typeof StudentIndexRoute
  '/superadmin/': typeof SuperadminIndexRoute
  '/teacher/': typeof TeacherIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/demands': typeof AdminDemandsRoute
  '/admin/esg': typeof AdminEsgRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/hr': typeof AdminHrRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/partnerships': typeof AdminPartnershipsRoute
  '/admin/research': typeof AdminResearchRoute
  '/admin/strategic': typeof AdminStrategicRoute
  '/director/academic': typeof DirectorAcademicRoute
  '/director/alerts': typeof DirectorAlertsRoute
  '/director/approvals': typeof DirectorApprovalsRoute
  '/director/dashboard': typeof DirectorDashboardRoute
  '/director/financial': typeof DirectorFinancialRoute
  '/director/meetings': typeof DirectorMeetingsRoute
  '/director/messages': typeof DirectorMessagesRoute
  '/director/reports': typeof DirectorReportsRoute
  '/director/staff': typeof DirectorStaffRoute
  '/student/attendance': typeof StudentAttendanceRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/documents': typeof StudentDocumentsRoute
  '/student/educational-path': typeof StudentEducationalPathRoute
  '/student/enrollment': typeof StudentEnrollmentRoute
  '/student/forms': typeof StudentFormsRoute
  '/student/grades': typeof StudentGradesRoute
  '/student/internships': typeof StudentInternshipsRoute
  '/student/messages': typeof StudentMessagesRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/schedule': typeof StudentScheduleRoute
  '/student/student-life': typeof StudentStudentLifeRoute
  '/superadmin/academic': typeof SuperadminAcademicRoute
  '/superadmin/coordination': typeof SuperadminCoordinationRoute
  '/superadmin/dashboard': typeof SuperadminDashboardRoute
  '/superadmin/demands': typeof SuperadminDemandsRoute
  '/superadmin/employment-equity': typeof SuperadminEmploymentEquityRoute
  '/superadmin/financial': typeof SuperadminFinancialRoute
  '/superadmin/institutions': typeof SuperadminInstitutionsRoute
  '/superadmin/messages': typeof SuperadminMessagesRoute
  '/superadmin/monitoring': typeof SuperadminMonitoringRoute
  '/superadmin/offers': typeof SuperadminOffersRoute
  '/superadmin/predictions': typeof SuperadminPredictionsRoute
  '/superadmin/strategic': typeof SuperadminStrategicRoute
  '/superadmin/users': typeof SuperadminUsersRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/courses': typeof TeacherCoursesRoute
  '/teacher/dashboard': typeof TeacherDashboardRoute
  '/teacher/exams': typeof TeacherExamsRoute
  '/teacher/grades': typeof TeacherGradesRoute
  '/teacher/messages': typeof TeacherMessagesRoute
  '/teacher/reports': typeof TeacherReportsRoute
  '/teacher/satisfaction': typeof TeacherSatisfactionRoute
  '/teacher/students': typeof TeacherStudentsRoute
  '/admin': typeof AdminIndexRoute
  '/director': typeof DirectorIndexRoute
  '/student': typeof StudentIndexRoute
  '/superadmin': typeof SuperadminIndexRoute
  '/teacher': typeof TeacherIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/director': typeof DirectorRouteWithChildren
  '/student': typeof StudentRouteWithChildren
  '/superadmin': typeof SuperadminRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/demands': typeof AdminDemandsRoute
  '/admin/esg': typeof AdminEsgRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/hr': typeof AdminHrRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/partnerships': typeof AdminPartnershipsRoute
  '/admin/research': typeof AdminResearchRoute
  '/admin/strategic': typeof AdminStrategicRoute
  '/director/academic': typeof DirectorAcademicRoute
  '/director/alerts': typeof DirectorAlertsRoute
  '/director/approvals': typeof DirectorApprovalsRoute
  '/director/dashboard': typeof DirectorDashboardRoute
  '/director/financial': typeof DirectorFinancialRoute
  '/director/meetings': typeof DirectorMeetingsRoute
  '/director/messages': typeof DirectorMessagesRoute
  '/director/reports': typeof DirectorReportsRoute
  '/director/staff': typeof DirectorStaffRoute
  '/student/attendance': typeof StudentAttendanceRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/documents': typeof StudentDocumentsRoute
  '/student/educational-path': typeof StudentEducationalPathRoute
  '/student/enrollment': typeof StudentEnrollmentRoute
  '/student/forms': typeof StudentFormsRoute
  '/student/grades': typeof StudentGradesRoute
  '/student/internships': typeof StudentInternshipsRoute
  '/student/messages': typeof StudentMessagesRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/schedule': typeof StudentScheduleRoute
  '/student/student-life': typeof StudentStudentLifeRoute
  '/superadmin/academic': typeof SuperadminAcademicRoute
  '/superadmin/coordination': typeof SuperadminCoordinationRoute
  '/superadmin/dashboard': typeof SuperadminDashboardRoute
  '/superadmin/demands': typeof SuperadminDemandsRoute
  '/superadmin/employment-equity': typeof SuperadminEmploymentEquityRoute
  '/superadmin/financial': typeof SuperadminFinancialRoute
  '/superadmin/institutions': typeof SuperadminInstitutionsRoute
  '/superadmin/messages': typeof SuperadminMessagesRoute
  '/superadmin/monitoring': typeof SuperadminMonitoringRoute
  '/superadmin/offers': typeof SuperadminOffersRoute
  '/superadmin/predictions': typeof SuperadminPredictionsRoute
  '/superadmin/strategic': typeof SuperadminStrategicRoute
  '/superadmin/users': typeof SuperadminUsersRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/courses': typeof TeacherCoursesRoute
  '/teacher/dashboard': typeof TeacherDashboardRoute
  '/teacher/exams': typeof TeacherExamsRoute
  '/teacher/grades': typeof TeacherGradesRoute
  '/teacher/messages': typeof TeacherMessagesRoute
  '/teacher/reports': typeof TeacherReportsRoute
  '/teacher/satisfaction': typeof TeacherSatisfactionRoute
  '/teacher/students': typeof TeacherStudentsRoute
  '/admin/': typeof AdminIndexRoute
  '/director/': typeof DirectorIndexRoute
  '/student/': typeof StudentIndexRoute
  '/superadmin/': typeof SuperadminIndexRoute
  '/teacher/': typeof TeacherIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/director'
    | '/student'
    | '/superadmin'
    | '/teacher'
    | '/admin/dashboard'
    | '/admin/demands'
    | '/admin/esg'
    | '/admin/finance'
    | '/admin/hr'
    | '/admin/messages'
    | '/admin/partnerships'
    | '/admin/research'
    | '/admin/strategic'
    | '/director/academic'
    | '/director/alerts'
    | '/director/approvals'
    | '/director/dashboard'
    | '/director/financial'
    | '/director/meetings'
    | '/director/messages'
    | '/director/reports'
    | '/director/staff'
    | '/student/attendance'
    | '/student/dashboard'
    | '/student/documents'
    | '/student/educational-path'
    | '/student/enrollment'
    | '/student/forms'
    | '/student/grades'
    | '/student/internships'
    | '/student/messages'
    | '/student/profile'
    | '/student/schedule'
    | '/student/student-life'
    | '/superadmin/academic'
    | '/superadmin/coordination'
    | '/superadmin/dashboard'
    | '/superadmin/demands'
    | '/superadmin/employment-equity'
    | '/superadmin/financial'
    | '/superadmin/institutions'
    | '/superadmin/messages'
    | '/superadmin/monitoring'
    | '/superadmin/offers'
    | '/superadmin/predictions'
    | '/superadmin/strategic'
    | '/superadmin/users'
    | '/teacher/attendance'
    | '/teacher/courses'
    | '/teacher/dashboard'
    | '/teacher/exams'
    | '/teacher/grades'
    | '/teacher/messages'
    | '/teacher/reports'
    | '/teacher/satisfaction'
    | '/teacher/students'
    | '/admin/'
    | '/director/'
    | '/student/'
    | '/superadmin/'
    | '/teacher/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/dashboard'
    | '/admin/demands'
    | '/admin/esg'
    | '/admin/finance'
    | '/admin/hr'
    | '/admin/messages'
    | '/admin/partnerships'
    | '/admin/research'
    | '/admin/strategic'
    | '/director/academic'
    | '/director/alerts'
    | '/director/approvals'
    | '/director/dashboard'
    | '/director/financial'
    | '/director/meetings'
    | '/director/messages'
    | '/director/reports'
    | '/director/staff'
    | '/student/attendance'
    | '/student/dashboard'
    | '/student/documents'
    | '/student/educational-path'
    | '/student/enrollment'
    | '/student/forms'
    | '/student/grades'
    | '/student/internships'
    | '/student/messages'
    | '/student/profile'
    | '/student/schedule'
    | '/student/student-life'
    | '/superadmin/academic'
    | '/superadmin/coordination'
    | '/superadmin/dashboard'
    | '/superadmin/demands'
    | '/superadmin/employment-equity'
    | '/superadmin/financial'
    | '/superadmin/institutions'
    | '/superadmin/messages'
    | '/superadmin/monitoring'
    | '/superadmin/offers'
    | '/superadmin/predictions'
    | '/superadmin/strategic'
    | '/superadmin/users'
    | '/teacher/attendance'
    | '/teacher/courses'
    | '/teacher/dashboard'
    | '/teacher/exams'
    | '/teacher/grades'
    | '/teacher/messages'
    | '/teacher/reports'
    | '/teacher/satisfaction'
    | '/teacher/students'
    | '/admin'
    | '/director'
    | '/student'
    | '/superadmin'
    | '/teacher'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/director'
    | '/student'
    | '/superadmin'
    | '/teacher'
    | '/admin/dashboard'
    | '/admin/demands'
    | '/admin/esg'
    | '/admin/finance'
    | '/admin/hr'
    | '/admin/messages'
    | '/admin/partnerships'
    | '/admin/research'
    | '/admin/strategic'
    | '/director/academic'
    | '/director/alerts'
    | '/director/approvals'
    | '/director/dashboard'
    | '/director/financial'
    | '/director/meetings'
    | '/director/messages'
    | '/director/reports'
    | '/director/staff'
    | '/student/attendance'
    | '/student/dashboard'
    | '/student/documents'
    | '/student/educational-path'
    | '/student/enrollment'
    | '/student/forms'
    | '/student/grades'
    | '/student/internships'
    | '/student/messages'
    | '/student/profile'
    | '/student/schedule'
    | '/student/student-life'
    | '/superadmin/academic'
    | '/superadmin/coordination'
    | '/superadmin/dashboard'
    | '/superadmin/demands'
    | '/superadmin/employment-equity'
    | '/superadmin/financial'
    | '/superadmin/institutions'
    | '/superadmin/messages'
    | '/superadmin/monitoring'
    | '/superadmin/offers'
    | '/superadmin/predictions'
    | '/superadmin/strategic'
    | '/superadmin/users'
    | '/teacher/attendance'
    | '/teacher/courses'
    | '/teacher/dashboard'
    | '/teacher/exams'
    | '/teacher/grades'
    | '/teacher/messages'
    | '/teacher/reports'
    | '/teacher/satisfaction'
    | '/teacher/students'
    | '/admin/'
    | '/director/'
    | '/student/'
    | '/superadmin/'
    | '/teacher/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DirectorRoute: typeof DirectorRouteWithChildren
  StudentRoute: typeof StudentRouteWithChildren
  SuperadminRoute: typeof SuperadminRouteWithChildren
  TeacherRoute: typeof TeacherRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin': {
      id: '/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof SuperadminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/director': {
      id: '/director'
      path: '/director'
      fullPath: '/director'
      preLoaderRoute: typeof DirectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/superadmin/': {
      id: '/superadmin/'
      path: '/'
      fullPath: '/superadmin/'
      preLoaderRoute: typeof SuperadminIndexRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/director/': {
      id: '/director/'
      path: '/'
      fullPath: '/director/'
      preLoaderRoute: typeof DirectorIndexRouteImport
      parentRoute: typeof DirectorRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/teacher/students': {
      id: '/teacher/students'
      path: '/students'
      fullPath: '/teacher/students'
      preLoaderRoute: typeof TeacherStudentsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/satisfaction': {
      id: '/teacher/satisfaction'
      path: '/satisfaction'
      fullPath: '/teacher/satisfaction'
      preLoaderRoute: typeof TeacherSatisfactionRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/reports': {
      id: '/teacher/reports'
      path: '/reports'
      fullPath: '/teacher/reports'
      preLoaderRoute: typeof TeacherReportsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/messages': {
      id: '/teacher/messages'
      path: '/messages'
      fullPath: '/teacher/messages'
      preLoaderRoute: typeof TeacherMessagesRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/grades': {
      id: '/teacher/grades'
      path: '/grades'
      fullPath: '/teacher/grades'
      preLoaderRoute: typeof TeacherGradesRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/exams': {
      id: '/teacher/exams'
      path: '/exams'
      fullPath: '/teacher/exams'
      preLoaderRoute: typeof TeacherExamsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/dashboard': {
      id: '/teacher/dashboard'
      path: '/dashboard'
      fullPath: '/teacher/dashboard'
      preLoaderRoute: typeof TeacherDashboardRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/courses': {
      id: '/teacher/courses'
      path: '/courses'
      fullPath: '/teacher/courses'
      preLoaderRoute: typeof TeacherCoursesRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/attendance': {
      id: '/teacher/attendance'
      path: '/attendance'
      fullPath: '/teacher/attendance'
      preLoaderRoute: typeof TeacherAttendanceRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/superadmin/users': {
      id: '/superadmin/users'
      path: '/users'
      fullPath: '/superadmin/users'
      preLoaderRoute: typeof SuperadminUsersRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/strategic': {
      id: '/superadmin/strategic'
      path: '/strategic'
      fullPath: '/superadmin/strategic'
      preLoaderRoute: typeof SuperadminStrategicRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/predictions': {
      id: '/superadmin/predictions'
      path: '/predictions'
      fullPath: '/superadmin/predictions'
      preLoaderRoute: typeof SuperadminPredictionsRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/offers': {
      id: '/superadmin/offers'
      path: '/offers'
      fullPath: '/superadmin/offers'
      preLoaderRoute: typeof SuperadminOffersRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/monitoring': {
      id: '/superadmin/monitoring'
      path: '/monitoring'
      fullPath: '/superadmin/monitoring'
      preLoaderRoute: typeof SuperadminMonitoringRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/messages': {
      id: '/superadmin/messages'
      path: '/messages'
      fullPath: '/superadmin/messages'
      preLoaderRoute: typeof SuperadminMessagesRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/institutions': {
      id: '/superadmin/institutions'
      path: '/institutions'
      fullPath: '/superadmin/institutions'
      preLoaderRoute: typeof SuperadminInstitutionsRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/financial': {
      id: '/superadmin/financial'
      path: '/financial'
      fullPath: '/superadmin/financial'
      preLoaderRoute: typeof SuperadminFinancialRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/employment-equity': {
      id: '/superadmin/employment-equity'
      path: '/employment-equity'
      fullPath: '/superadmin/employment-equity'
      preLoaderRoute: typeof SuperadminEmploymentEquityRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/demands': {
      id: '/superadmin/demands'
      path: '/demands'
      fullPath: '/superadmin/demands'
      preLoaderRoute: typeof SuperadminDemandsRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/dashboard': {
      id: '/superadmin/dashboard'
      path: '/dashboard'
      fullPath: '/superadmin/dashboard'
      preLoaderRoute: typeof SuperadminDashboardRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/coordination': {
      id: '/superadmin/coordination'
      path: '/coordination'
      fullPath: '/superadmin/coordination'
      preLoaderRoute: typeof SuperadminCoordinationRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/academic': {
      id: '/superadmin/academic'
      path: '/academic'
      fullPath: '/superadmin/academic'
      preLoaderRoute: typeof SuperadminAcademicRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/student/student-life': {
      id: '/student/student-life'
      path: '/student-life'
      fullPath: '/student/student-life'
      preLoaderRoute: typeof StudentStudentLifeRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/schedule': {
      id: '/student/schedule'
      path: '/schedule'
      fullPath: '/student/schedule'
      preLoaderRoute: typeof StudentScheduleRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/messages': {
      id: '/student/messages'
      path: '/messages'
      fullPath: '/student/messages'
      preLoaderRoute: typeof StudentMessagesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/internships': {
      id: '/student/internships'
      path: '/internships'
      fullPath: '/student/internships'
      preLoaderRoute: typeof StudentInternshipsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/grades': {
      id: '/student/grades'
      path: '/grades'
      fullPath: '/student/grades'
      preLoaderRoute: typeof StudentGradesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/forms': {
      id: '/student/forms'
      path: '/forms'
      fullPath: '/student/forms'
      preLoaderRoute: typeof StudentFormsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/enrollment': {
      id: '/student/enrollment'
      path: '/enrollment'
      fullPath: '/student/enrollment'
      preLoaderRoute: typeof StudentEnrollmentRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/educational-path': {
      id: '/student/educational-path'
      path: '/educational-path'
      fullPath: '/student/educational-path'
      preLoaderRoute: typeof StudentEducationalPathRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/documents': {
      id: '/student/documents'
      path: '/documents'
      fullPath: '/student/documents'
      preLoaderRoute: typeof StudentDocumentsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/dashboard': {
      id: '/student/dashboard'
      path: '/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/attendance': {
      id: '/student/attendance'
      path: '/attendance'
      fullPath: '/student/attendance'
      preLoaderRoute: typeof StudentAttendanceRouteImport
      parentRoute: typeof StudentRoute
    }
    '/director/staff': {
      id: '/director/staff'
      path: '/staff'
      fullPath: '/director/staff'
      preLoaderRoute: typeof DirectorStaffRouteImport
      parentRoute: typeof DirectorRoute
    }
    '/director/reports': {
      id: '/director/reports'
      path: '/reports'
      fullPath: '/director/reports'
      preLoaderRoute: typeof DirectorReportsRouteImport
      parentRoute: typeof DirectorRoute
    }
    '/director/messages': {
      id: '/director/messages'
      path: '/messages'
      fullPath: '/director/messages'
      preLoaderRoute: typeof DirectorMessagesRouteImport
      parentRoute: typeof DirectorRoute
    }
    '/director/meetings': {
      id: '/director/meetings'
      path: '/meetings'
      fullPath: '/director/meetings'
      preLoaderRoute: typeof DirectorMeetingsRouteImport
      parentRoute: typeof DirectorRoute
    }
    '/director/financial': {
      id: '/director/financial'
      path: '/financial'
      fullPath: '/director/financial'
      preLoaderRoute: typeof DirectorFinancialRouteImport
      parentRoute: typeof DirectorRoute
    }
    '/director/dashboard': {
      id: '/director/dashboard'
      path: '/dashboard'
      fullPath: '/director/dashboard'
      preLoaderRoute: typeof DirectorDashboardRouteImport
      parentRoute: typeof DirectorRoute
    }
    '/director/approvals': {
      id: '/director/approvals'
      path: '/approvals'
      fullPath: '/director/approvals'
      preLoaderRoute: typeof DirectorApprovalsRouteImport
      parentRoute: typeof DirectorRoute
    }
    '/director/alerts': {
      id: '/director/alerts'
      path: '/alerts'
      fullPath: '/director/alerts'
      preLoaderRoute: typeof DirectorAlertsRouteImport
      parentRoute: typeof DirectorRoute
    }
    '/director/academic': {
      id: '/director/academic'
      path: '/academic'
      fullPath: '/director/academic'
      preLoaderRoute: typeof DirectorAcademicRouteImport
      parentRoute: typeof DirectorRoute
    }
    '/admin/strategic': {
      id: '/admin/strategic'
      path: '/strategic'
      fullPath: '/admin/strategic'
      preLoaderRoute: typeof AdminStrategicRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/research': {
      id: '/admin/research'
      path: '/research'
      fullPath: '/admin/research'
      preLoaderRoute: typeof AdminResearchRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/partnerships': {
      id: '/admin/partnerships'
      path: '/partnerships'
      fullPath: '/admin/partnerships'
      preLoaderRoute: typeof AdminPartnershipsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hr': {
      id: '/admin/hr'
      path: '/hr'
      fullPath: '/admin/hr'
      preLoaderRoute: typeof AdminHrRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/esg': {
      id: '/admin/esg'
      path: '/esg'
      fullPath: '/admin/esg'
      preLoaderRoute: typeof AdminEsgRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/demands': {
      id: '/admin/demands'
      path: '/demands'
      fullPath: '/admin/demands'
      preLoaderRoute: typeof AdminDemandsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDemandsRoute: typeof AdminDemandsRoute
  AdminEsgRoute: typeof AdminEsgRoute
  AdminFinanceRoute: typeof AdminFinanceRoute
  AdminHrRoute: typeof AdminHrRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminPartnershipsRoute: typeof AdminPartnershipsRoute
  AdminResearchRoute: typeof AdminResearchRoute
  AdminStrategicRoute: typeof AdminStrategicRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDemandsRoute: AdminDemandsRoute,
  AdminEsgRoute: AdminEsgRoute,
  AdminFinanceRoute: AdminFinanceRoute,
  AdminHrRoute: AdminHrRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminPartnershipsRoute: AdminPartnershipsRoute,
  AdminResearchRoute: AdminResearchRoute,
  AdminStrategicRoute: AdminStrategicRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DirectorRouteChildren {
  DirectorAcademicRoute: typeof DirectorAcademicRoute
  DirectorAlertsRoute: typeof DirectorAlertsRoute
  DirectorApprovalsRoute: typeof DirectorApprovalsRoute
  DirectorDashboardRoute: typeof DirectorDashboardRoute
  DirectorFinancialRoute: typeof DirectorFinancialRoute
  DirectorMeetingsRoute: typeof DirectorMeetingsRoute
  DirectorMessagesRoute: typeof DirectorMessagesRoute
  DirectorReportsRoute: typeof DirectorReportsRoute
  DirectorStaffRoute: typeof DirectorStaffRoute
  DirectorIndexRoute: typeof DirectorIndexRoute
}

const DirectorRouteChildren: DirectorRouteChildren = {
  DirectorAcademicRoute: DirectorAcademicRoute,
  DirectorAlertsRoute: DirectorAlertsRoute,
  DirectorApprovalsRoute: DirectorApprovalsRoute,
  DirectorDashboardRoute: DirectorDashboardRoute,
  DirectorFinancialRoute: DirectorFinancialRoute,
  DirectorMeetingsRoute: DirectorMeetingsRoute,
  DirectorMessagesRoute: DirectorMessagesRoute,
  DirectorReportsRoute: DirectorReportsRoute,
  DirectorStaffRoute: DirectorStaffRoute,
  DirectorIndexRoute: DirectorIndexRoute,
}

const DirectorRouteWithChildren = DirectorRoute._addFileChildren(
  DirectorRouteChildren,
)

interface StudentRouteChildren {
  StudentAttendanceRoute: typeof StudentAttendanceRoute
  StudentDashboardRoute: typeof StudentDashboardRoute
  StudentDocumentsRoute: typeof StudentDocumentsRoute
  StudentEducationalPathRoute: typeof StudentEducationalPathRoute
  StudentEnrollmentRoute: typeof StudentEnrollmentRoute
  StudentFormsRoute: typeof StudentFormsRoute
  StudentGradesRoute: typeof StudentGradesRoute
  StudentInternshipsRoute: typeof StudentInternshipsRoute
  StudentMessagesRoute: typeof StudentMessagesRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentScheduleRoute: typeof StudentScheduleRoute
  StudentStudentLifeRoute: typeof StudentStudentLifeRoute
  StudentIndexRoute: typeof StudentIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentAttendanceRoute: StudentAttendanceRoute,
  StudentDashboardRoute: StudentDashboardRoute,
  StudentDocumentsRoute: StudentDocumentsRoute,
  StudentEducationalPathRoute: StudentEducationalPathRoute,
  StudentEnrollmentRoute: StudentEnrollmentRoute,
  StudentFormsRoute: StudentFormsRoute,
  StudentGradesRoute: StudentGradesRoute,
  StudentInternshipsRoute: StudentInternshipsRoute,
  StudentMessagesRoute: StudentMessagesRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentScheduleRoute: StudentScheduleRoute,
  StudentStudentLifeRoute: StudentStudentLifeRoute,
  StudentIndexRoute: StudentIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

interface SuperadminRouteChildren {
  SuperadminAcademicRoute: typeof SuperadminAcademicRoute
  SuperadminCoordinationRoute: typeof SuperadminCoordinationRoute
  SuperadminDashboardRoute: typeof SuperadminDashboardRoute
  SuperadminDemandsRoute: typeof SuperadminDemandsRoute
  SuperadminEmploymentEquityRoute: typeof SuperadminEmploymentEquityRoute
  SuperadminFinancialRoute: typeof SuperadminFinancialRoute
  SuperadminInstitutionsRoute: typeof SuperadminInstitutionsRoute
  SuperadminMessagesRoute: typeof SuperadminMessagesRoute
  SuperadminMonitoringRoute: typeof SuperadminMonitoringRoute
  SuperadminOffersRoute: typeof SuperadminOffersRoute
  SuperadminPredictionsRoute: typeof SuperadminPredictionsRoute
  SuperadminStrategicRoute: typeof SuperadminStrategicRoute
  SuperadminUsersRoute: typeof SuperadminUsersRoute
  SuperadminIndexRoute: typeof SuperadminIndexRoute
}

const SuperadminRouteChildren: SuperadminRouteChildren = {
  SuperadminAcademicRoute: SuperadminAcademicRoute,
  SuperadminCoordinationRoute: SuperadminCoordinationRoute,
  SuperadminDashboardRoute: SuperadminDashboardRoute,
  SuperadminDemandsRoute: SuperadminDemandsRoute,
  SuperadminEmploymentEquityRoute: SuperadminEmploymentEquityRoute,
  SuperadminFinancialRoute: SuperadminFinancialRoute,
  SuperadminInstitutionsRoute: SuperadminInstitutionsRoute,
  SuperadminMessagesRoute: SuperadminMessagesRoute,
  SuperadminMonitoringRoute: SuperadminMonitoringRoute,
  SuperadminOffersRoute: SuperadminOffersRoute,
  SuperadminPredictionsRoute: SuperadminPredictionsRoute,
  SuperadminStrategicRoute: SuperadminStrategicRoute,
  SuperadminUsersRoute: SuperadminUsersRoute,
  SuperadminIndexRoute: SuperadminIndexRoute,
}

const SuperadminRouteWithChildren = SuperadminRoute._addFileChildren(
  SuperadminRouteChildren,
)

interface TeacherRouteChildren {
  TeacherAttendanceRoute: typeof TeacherAttendanceRoute
  TeacherCoursesRoute: typeof TeacherCoursesRoute
  TeacherDashboardRoute: typeof TeacherDashboardRoute
  TeacherExamsRoute: typeof TeacherExamsRoute
  TeacherGradesRoute: typeof TeacherGradesRoute
  TeacherMessagesRoute: typeof TeacherMessagesRoute
  TeacherReportsRoute: typeof TeacherReportsRoute
  TeacherSatisfactionRoute: typeof TeacherSatisfactionRoute
  TeacherStudentsRoute: typeof TeacherStudentsRoute
  TeacherIndexRoute: typeof TeacherIndexRoute
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherAttendanceRoute: TeacherAttendanceRoute,
  TeacherCoursesRoute: TeacherCoursesRoute,
  TeacherDashboardRoute: TeacherDashboardRoute,
  TeacherExamsRoute: TeacherExamsRoute,
  TeacherGradesRoute: TeacherGradesRoute,
  TeacherMessagesRoute: TeacherMessagesRoute,
  TeacherReportsRoute: TeacherReportsRoute,
  TeacherSatisfactionRoute: TeacherSatisfactionRoute,
  TeacherStudentsRoute: TeacherStudentsRoute,
  TeacherIndexRoute: TeacherIndexRoute,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DirectorRoute: DirectorRouteWithChildren,
  StudentRoute: StudentRouteWithChildren,
  SuperadminRoute: SuperadminRouteWithChildren,
  TeacherRoute: TeacherRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
